# Generated by Django 4.2.16 on 2026-06-29 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('couleur', models.CharField(default='#14706b', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tags_entreprise',
            },
        ),
        migrations.CreateModel(
            name='SessionImpersonate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.TextField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonations_faites', to=settings.AUTH_USER_MODEL)),
                ('user_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonations_subies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessions_impersonate',
            },
        ),
        migrations.CreateModel(
            name='NoteEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('importante', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_admin', to='accounts.entreprise')),
            ],
            options={
                'db_table': 'notes_entreprise',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Deconnexion'), ('CREATION', 'Creation'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('VALIDATION', 'Validation'), ('REFUS', 'Refus'), ('IMPERSONATE', 'Impersonification'), ('EXPORT', 'Export'), ('AUTRE', 'Autre')], max_length=20)),
                ('objet_type', models.CharField(blank=True, help_text="Type d'objet (User, Entreprise, etc.)", max_length=100)),
                ('objet_id', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logs_audit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntrepriseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='accounts.entreprise')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.tagentreprise')),
            ],
            options={
                'db_table': 'entreprise_tags',
                'unique_together': {('entreprise', 'tag')},
            },
        ),
    ]
