# Generated by Django 4.2.16 on 2026-06-29 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('type_reduction', models.CharField(choices=[('POURCENTAGE', 'Pourcentage'), ('MONTANT', 'Montant fixe'), ('JOURS_GRATUITS', 'Jours gratuits')], default='POURCENTAGE', max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('max_utilisations', models.IntegerField(default=100)),
                ('nb_utilisations', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('forfaits_eligibles', models.ManyToManyField(blank=True, help_text='Vide = tous les forfaits', to='abonnements.forfait')),
            ],
            options={
                'db_table': 'coupons_promo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParametreSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('valeur', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('type_valeur', models.CharField(choices=[('TEXT', 'Texte'), ('NUMBER', 'Nombre'), ('BOOLEAN', 'Booleen'), ('JSON', 'JSON')], default='TEXT', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parametres_systeme',
            },
        ),
        migrations.CreateModel(
            name='UtilisationCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduction_appliquee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations', to='admin_panel.couponpromo')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.entreprise')),
                ('paiement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abonnements.paiement')),
            ],
            options={
                'db_table': 'utilisations_coupons',
            },
        ),
        migrations.CreateModel(
            name='CampagneEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('cible_toutes', models.BooleanField(default=True)),
                ('cible_actives', models.BooleanField(default=True, help_text='Uniquement entreprises avec abonnement actif')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PROGRAMMEE', 'Programmee'), ('ENVOYEE', 'Envoyee'), ('ANNULEE', 'Annulee')], default='BROUILLON', max_length=20)),
                ('nb_destinataires', models.IntegerField(default=0)),
                ('nb_envoyes', models.IntegerField(default=0)),
                ('date_envoi_prevue', models.DateTimeField(blank=True, null=True)),
                ('date_envoi_effective', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cible_forfaits', models.ManyToManyField(blank=True, to='abonnements.forfait')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprises_destinataires', models.ManyToManyField(blank=True, related_name='campagnes_recues', to='accounts.entreprise')),
            ],
            options={
                'db_table': 'campagnes_email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='backups/')),
                ('taille_mo', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backups_base',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RapportMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='rapports/%Y/')),
                ('revenus_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nb_nouveaux_clients', models.IntegerField(default=0)),
                ('nb_abonnements_actifs', models.IntegerField(default=0)),
                ('nb_paiements', models.IntegerField(default=0)),
                ('mrr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('churn_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rapports_mensuels',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('mois', 'annee')},
            },
        ),
    ]
