# Generated by Django 4.2.16 on 2026-06-29 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureOCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='factures/%Y/%m/')),
                ('nom_original', models.CharField(max_length=255)),
                ('texte_brut', models.TextField(blank=True)),
                ('fournisseur', models.CharField(blank=True, max_length=200)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_facture', models.DateField(blank=True, null=True)),
                ('compte_suggere', models.CharField(blank=True, max_length=10)),
                ('libelle_suggere', models.CharField(blank=True, max_length=200)),
                ('score_confiance', models.FloatField(default=0.0)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TERMINE', 'Termine'), ('ERREUR', 'Erreur')], default='EN_ATTENTE', max_length=20)),
                ('ecriture_creee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='accounts.entreprise')),
            ],
            options={
                'db_table': 'factures_ocr',
                'ordering': ['-created_at'],
            },
        ),
    ]
