# Generated by Django 4.2.16 on 2026-06-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureocr',
            name='devise',
            field=models.CharField(choices=[('XOF', 'FCFA (XOF)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dollar US (USD)'), ('GBP', 'Livre Sterling (GBP)'), ('MAD', 'Dirham Marocain (MAD)'), ('CAD', 'Dollar Canadien (CAD)'), ('CNY', 'Yuan (CNY)'), ('CHF', 'Franc Suisse (CHF)'), ('JPY', 'Yen (JPY)'), ('NGN', 'Naira (NGN)'), ('GHS', 'Cedi (GHS)')], default='XOF', max_length=10),
        ),
        migrations.AddField(
            model_name='factureocr',
            name='montant_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Montant dans la devise d'origine", max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='factureocr',
            name='taux_change',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='factureocr',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant en FCFA (converti)', max_digits=15, null=True),
        ),
    ]
