# Generated by Django 4.2.16 on 2026-06-29 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expire'), ('SUSPENDU', 'Suspendu'), ('ANNULE', 'Annule')], default='ACTIF', max_length=20)),
                ('auto_renouvellement', models.BooleanField(default=False)),
                ('factures_ocr_utilisees', models.IntegerField(default=0)),
                ('ecritures_utilisees', models.IntegerField(default=0)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='accounts.entreprise')),
            ],
            options={
                'db_table': 'abonnements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('FREEMIUM', 'Freemium (Essai)'), ('STARTER', 'Starter'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise'), ('ANNUEL', 'Annuel')], max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_jours', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('max_factures_ocr_mois', models.IntegerField(default=10)),
                ('max_utilisateurs', models.IntegerField(default=1)),
                ('max_ecritures_mois', models.IntegerField(default=50)),
                ('rapprochement_bancaire', models.BooleanField(default=False)),
                ('reporting_avance', models.BooleanField(default=False)),
                ('support_prioritaire', models.BooleanField(default=False)),
                ('export_illimite', models.BooleanField(default=False)),
                ('couleur', models.CharField(default='#14706b', max_length=20)),
                ('icone', models.CharField(default='bi-star', max_length=50)),
                ('populaire', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'forfaits',
                'ordering': ['ordre', 'prix'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money (Orange/MTN/Moov)'), ('CARTE', 'Carte bancaire'), ('VIREMENT', 'Virement bancaire'), ('ESPECES', 'Especes'), ('CHEQUE', 'Cheque')], default='MOBILE_MONEY', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Valide'), ('REFUSE', 'Refuse'), ('REMBOURSE', 'Rembourse')], default='EN_ATTENTE', max_length=20)),
                ('numero_transaction', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valide_at', models.DateTimeField(blank=True, null=True)),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonnements.abonnement')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='accounts.entreprise')),
                ('forfait', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abonnements.forfait')),
                ('paye_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='abonnement',
            name='forfait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abonnements.forfait'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='renouvelle_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonnements.abonnement'),
        ),
    ]
