# Generated by Django 4.2.16 on 2026-06-29 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeuilAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('TRESORERIE_BASSE', 'Tresorerie basse'), ('CREANCE_ELEVEE', 'Creances elevees'), ('DETTE_ELEVEE', 'Dettes elevees'), ('IMPAYE', 'Facture impayee')], max_length=30)),
                ('seuil', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actif', models.BooleanField(default=True)),
                ('notif_email', models.BooleanField(default=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seuils', to='accounts.entreprise')),
            ],
            options={
                'db_table': 'seuils_alertes',
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Avertissement'), ('DANGER', 'Critique')], default='WARNING', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='accounts.entreprise')),
            ],
            options={
                'db_table': 'alertes',
                'ordering': ['-created_at'],
            },
        ),
    ]
