# Generated by Django 4.2.16 on 2026-06-29 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('libelle', models.CharField(max_length=200)),
                ('classe', models.IntegerField()),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='accounts.entreprise')),
            ],
            options={
                'db_table': 'comptes',
                'ordering': ['numero'],
                'unique_together': {('entreprise', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Ecriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ecriture', models.DateField()),
                ('numero_piece', models.CharField(blank=True, max_length=50)),
                ('libelle', models.CharField(max_length=300)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validee'), ('AUTO', 'Auto (OCR)')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compte_credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures_credit', to='comptabilite.compte')),
                ('compte_debit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures_debit', to='comptabilite.compte')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='accounts.entreprise')),
            ],
            options={
                'db_table': 'ecritures',
                'ordering': ['-date_ecriture'],
            },
        ),
    ]
