# Generated by Django 4.2.16 on 2026-06-29 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('banque', models.CharField(default='Banque', max_length=100)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('nb_operations', models.IntegerField(default=0)),
                ('nb_rapprochees', models.IntegerField(default=0)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves', to='accounts.entreprise')),
            ],
            options={
                'db_table': 'releves_bancaires',
                'ordering': ['-date_import'],
            },
        ),
        migrations.CreateModel(
            name='OperationBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateField()),
                ('libelle', models.CharField(max_length=300)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sens', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], default='DEBIT', max_length=10)),
                ('score_rapprochement', models.FloatField(default=0.0)),
                ('rapprochee', models.BooleanField(default=False)),
                ('suggeree', models.BooleanField(default=False)),
                ('ecriture_associee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_rapprochees', to='comptabilite.ecriture')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.entreprise')),
                ('releve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='rapprochement.relevebancaire')),
            ],
            options={
                'db_table': 'operations_bancaires',
                'ordering': ['-date_operation'],
            },
        ),
    ]
